debug: true
spring:
  application:
    name: devspace
  datasource:
    url: jdbc:h2:file:./data/devspace;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false